project:
  type: default
#  output-dir: "_output_"
  lib-dir: "libs"
  preview:
    host: localhost
    port: 4000
    browser: false

default:
  page-layout: article
#  body-classes: "page-article body body-article"
#  # removido porque o python jรก adiciona as classes pelo template

  chapters:
  - artigo.md

format:
  html:
    date: today
    lang: "pt-BR"
    page-layout: article
    toc: false
    anchor-sections: false
    code-link: false
    number-sections: false