project:
  type: default
  output-dir: "../artefatos"
  lib-dir: "libs"
  preview:
    host: localhost
    port: 4000
    browser: false

default:
  chapters:
    - artigo.md

format:
  html:
    page-layout: article
    date: today
    lang: "pt-BR"
    toc: false
    anchor-sections: false
    code-link: false
    number-sections: false
