project:
  type: default
  output-dir: "docs"
  lib-dir: "libs"
  preview:
    port: 4200
    browser: false

default:
  chapters:
  - artigo.md

format:
  html:
    toc: false
    anchor-sections: false
    code-link: false
    number-sections: false