project:
  type: default
  output-dir: "../docs"
  lib-dir: "libs"
  preview:
    host: localhost
    port: 4000
    browser: false

default:
  page-layout: article
  chapters:
  - artigo.md

format:
  html:
    toc: false
    anchor-sections: false
    code-link: false
    number-sections: false