project:
  type: default
  output-dir: "_output/"
  lib-dir: "libs"
  preview:
    host: localhost
    port: 4000
    browser: false

default:
  page-layout: article
  language: "pt-BR"
  lang: "pt-BR"

  chapters:
  - artigo.md

format:
  html:
    toc: false
    anchor-sections: false
    code-link: false
    number-sections: false