project:
  type: website
  output-dir: _site

website:
  title: "Artigos de InteligÃªncia Artificial"

format:
  html:
    toc: false
    anchor-sections: false
    code-link: false
    number-sections: false
