name: news_v3

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["**/artigo.qmd"]

permissions:
  contents: write
  pull-requests: read
  pages: write
  id-token: write

jobs:
  build-news:
    runs-on: ubuntu-latest
    steps:
      - name: Clona o Reposit√≥rio newshub
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/newshub
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main