name: news_v3

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["article/**/*.qmd", "article/**/*.yml", "article/*.html", "article/*.bib"]

permissions:
  contents: write
  pull-requests: read
  pages: write
  id-token: write

jobs:
  build-news:
    runs-on: ubuntu-latest
    environment:
      name: ENVIRONMENT
    env:
      TOKEN: ${{ secrets.TOKEN_REPO_SYNC }}
      USEREMAIL: ${{ secrets.USEREMAIL }}
      USERNAME: ${{ github.repository_owner }}
    steps:
      - name: Clona o Repositório newshub
        uses: actions/checkout@v4
        with:
          repository: ${{ env.USERNAME }}/newshub
          token: ${{ secrets.GITHUB_TOKEN }}
          path: "newshub"
          ref: main
          fetch-depth: 30

      - name: Detecta mudanças na pasta article
        id: newshub
        run: |
          echo "Detectando mudanças na pasta article/"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^article/' > arquivos.txt || touch arquivos.txt
          echo "Arquivos alterados em article/:"
          cat arquivos.txt || echo "Nenhum arquivo encontrado"
          if [ ! -s arquivos.txt ]; then
            echo "Nenhuma mudança detectada em article/. Encerrando o workflow."
            exit 0
          fi

      - name: Configura Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Renderiza notícias Quarto
        working-directory: newshub
        id: renderizar
        run: |
          quarto render article/ --no-execute --output-dir ../artefatos --to html

      - name: Limpa diretórios 'libs'
        working-directory: newshub
        run: |
          REMOVER="libs _libs _site site_libs index_files _book delete .quarto _quarto"
          for nome in $REMOVER; do
            find . -type d -name "$nome" -exec rm -rf {} +
            echo "Diretório '$nome' removido."
          done

      - name: Instalar dependencias do Python
        working-directory: newshub
        run: |
          python -m pip install --upgrade pip
          pip install -r run/requirements.txt

      - name: Criar pasta temporaria 'artefatos'
        run: |
          mkdir -p newshub/artefatos

      - name: Syncronizar pastas
        run: |
          rsync -av --update _docs/ newshub/artefatos 

      - name: Corrigir links para GitHub Pages - newshub
        working-directory: newshub
        run: |
          python run/article.py --basedir artefatos/artigo.html --outputdir newsroom/archive
     

      - name: Configurar credencias Git
        working-directory: newshub
        run: |
          git config --global user.name "${{ github.repository_owner }}"
          git config --global user.email "${{ secrets.USEREMAIL }}"
  
      - name: Verificar branch 'news'
        working-directory: newshub
        run: |
          if git show-ref --verify --quiet refs/heads/news; then
            echo "Branch local 'news' já existe."
            git checkout news
          elif git ls-remote --exit-code --heads origin news; then
            echo "Branch remota 'news' existe. Fazendo fetch e checkout."
            git fetch origin news:news
            git checkout news
          else
            echo "Branch 'news' não existe. Criando nova branch."
            git checkout -b news
          fi

      - name: Baixa Artefato para 'GitHub Pages'
        uses: actions/download-artifact@v4
        with:
          name: newsroom_renderizados
          path: "newshub/newsroom/"

      - name: Commit as mudanças
        working-directory: newshub
        run: |
          git add newsroom
          git commit -m "news: atualiza notícias renderizadas" || echo "Nenhuma mudança para commitar"

      - name: Push das mudanças
        working-directory: newshub
        run: |
          git push origin news:news --force

  cleanup: 
    needs: [build-news]
    runs-on: ubuntu-latest
    steps:
      - name: Deleta artefatos
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            newsroom_detectados
            newsroom_renderizados
            github-pages