name: "Renderizar Notícias - Quarto"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      [
        "article/**/*.qmd",
        "article/**/*.yml",
        "article/*.html",
        "article/*.bib",
        ".github/workflows/*newshub*.yml",
      ]

permissions:
  contents: write
  pull-requests: read
  pages: write
  id-token: write

jobs:
  detectar:
    runs-on: ubuntu-latest
    environment:
      name: ENVIRONMENT
    env:
      TOKEN_REPO_SYNC: ${{ secrets.TOKEN_REPO_SYNC }}
      USEREMAIL: ${{ secrets.USEREMAIL }}
      USERNAME: ${{ github.repository_owner }}
    steps:
      - name: Clona o Repositório newshub
        uses: actions/checkout@v4
        with:
          repository: ${{ env.USERNAME }}/newshub
          token: ${{ secrets.GITHUB_TOKEN }}
          path: newshub
          ref: main
          fetch-depth: 30

      - name: Detecta mudanças na pasta article/
        id: detecta_article
        run: |
          cd newshub
          echo "Detectando mudanças na pasta article/"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^article/' > arquivos.txt || touch arquivos.txt
          echo "Arquivos alterados em article/:"
          cat arquivos.txt || echo "Nenhum arquivo encontrado"

      - name: Salva pasta article/ como artefato
        uses: actions/upload-artifact@v4
        with:
          name: newsroom_detectados
          path: newshub/article

  renderizar:
    needs: [detectar]
    runs-on: ubuntu-latest
    steps:
      - name: Baixa artefato
        uses: actions/download-artifact@v4
        with:
          name: newsroom_detectados
          path: _newsroom

      - name: Configura Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Renderiza notícias Quarto
        working-directory: _newsroom
        id: renderizar
        run: |
          quarto render --no-execute --output-dir ../_docs --to html

      - name: Limpa diretórios '_libs'
        working-directory: _newsroom
        run: |
          remover="libs _libs _site site_libs delete outra_pasta"
          for nome in $remover; do
            find . -type d -name "$nome" -exec rm -rf {} +
          done

      - name: Exporta notícias renderizadas
        uses: actions/upload-artifact@v4
        with:
          name: newsroom_renderizados
          path: "./_docs"

  newshub:
    needs: [renderizar]
    runs-on: ubuntu-latest
    environment:
      name: ENVIRONMENT
    steps:
      - name: Clona o Repositório 'newshub'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: news
          path: newshub

      - name: Configurar credencias Git
        working-directory: newshub
        run: |
          git config --global user.name "${{ github.repository_owner }}"
          git config --global user.email "${{ secrets.USEREMAIL }}"

      - name: Baixar e configura o Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Instalar dependencias do Python
        working-directory: newshub
        run: |
          python -m pip install --upgrade pip
          pip install -r run/requirements.txt

      - name: Baixa Artefato para 'GitHub Pages'
        uses: actions/download-artifact@v4
        with:
          name: newsroom_renderizados
          path: "newshub/artefatos"

      - name: Corrigir links para GitHub Pages - newshub
        working-directory: newshub
        run: |
          python ./run/article.py --basedir ./artefatos/artigo.html --outputdir newsroom/archive

      - name: Commit e Push das mudanças
        working-directory: newshub
        run: |
          git add newsroom/archive
          git commit -m "Atualiza notícias renderizadas" || echo "Nenhuma mudança para commitar"
          git push origin news

      - name: Salva Artefato para GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: "./newshub/newsroom/archive"

      - name: Faz deploy para GitHub Pages - newshub
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages

  cleanup:
    needs: [newshub]
    runs-on: ubuntu-latest
    steps:
      - name: Deleta artefatos
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            newsroom_detectados
            newsroom_renderizados
            github-pages
